### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by lampo1024** [msmolka/ZNetCS.AspNetCore.IPFiltering#4]
@msmolka I got a fatal error as follows:

```csharp
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at AspNetCoreRateLimit.Bits.GetBitMask(Int32 sizeOfBuff, Int32 bitLen)
   at AspNetCoreRateLimit.IpAddressRange..ctor(String ipRangeString)
   at AspNetCoreRateLimit.IpAddressUtil.ContainsIp(List`1 ipRules, String clientIp)
   at AspNetCoreRateLimit.IpParser.ContainsIp(List`1 ipRules, String clientIp)
   at AspNetCoreRateLimit.IpRateLimitProcessor.IsWhitelisted(ClientRequestIdentity requestIdentity)
   at AspNetCoreRateLimit.RateLimitMiddleware`1.Invoke(HttpContext context)
   at ZNetCS.AspNetCore.IPFiltering.IPFilteringMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by msmolka** [comment]
Any detail? What is the config, how to reproduce?

**Comment by lampo1024** [comment]
```json
"IPFiltering": {
        "DefaultBlockLevel": "None",
        "HttpStatusCode": 404,
        "Whitelist": [],
        "Blacklist": [ "..." ],
        "IgnoredPaths": [],
        "PathOptions": []
    }
```

Here is my settings.

**Comment by lampo1024** [comment]
I use this library for a few days, everything is working fine, but dozens of minutes ago, this error occurred for all request. My website can't access any more.

**Comment by lampo1024** [comment]
I comment this line:

```csharp
// app.UseIpRateLimiting();
```
And it's back to normal.

**Comment by msmolka** [comment]
`"Blacklist": [ "..." ], ` is not valid config.

**Comment by lampo1024** [comment]
> 
> 
> `"Blacklist": [ "..." ], ` is not valid config.

"..." is real ip address, I omit here.

Here is all my config:

```json
"IPFiltering": {
        "DefaultBlockLevel": "None",
        "HttpStatusCode": 404,
        "Whitelist": [],
        "Blacklist": [ "35.210.215.110", "35.210.215.10-35.210.215.255","40.77.167.37","46.229.168.10-46.229.168.255","106.38.241.181","39.106.60.151","47.104.164.49","54.36.150.1-54.36.150.255","54.36.148.1-54.36.148.255","54.36.149.1-54.36.149.255","23.100.232.233","94.130.216.184" ],
        "IgnoredPaths": [],
        "PathOptions": []
    }
```

**Comment by msmolka** [comment]
`AspNetCoreRateLimit.RateLimitMiddleware` is not my package. This error is related to different one.
mine is 
`app.UseIPFiltering();`

**Comment by lampo1024** [comment]
Ok,got it.

**Comment by lampo1024** [comment]
Thank you for your reply.
